### ISSUE TITLE
Generator fails on yo torso-brec with "Error: spawn gulp ENOENT"

### ISSUE THREAD

**Issue by blakejwc** [vecnatechnologies/generator-torso-brec#20]
I was trying to build the yo generator, but can't tell from the error what is happening.
Node: v0.12.7
NPM: 2.13.3
Yo: 1.4.7

OS: Ubuntu 12

Here is the console output:

``` shell
$ yo torso-brec
copying: app/index.html
copying: app/home/homeView.js
copying: app/home/home-template.hbs
copying: app/home/_home.scss
copying: app/app.scss
copying: app/app.js
copying: app/router.js
copying: dist/.keepme
copying: package.json
copying: gulpfile.js
   create package.json
   create app/index.html
   create app/home/homeView.js
   create app/home/home-template.hbs
   create app/home/_home.scss
   create app/app.scss
   create app/app.js
   create app/router.js
   create dist/.keepme
   create gulpfile.js
   create .gitignore
npm WARN package.json your-torso-project@0.1.0 No description
npm WARN package.json your-torso-project@0.1.0 No repository field.
npm WARN package.json your-torso-project@0.1.0 No README data
npm WARN package.json your-torso-project@0.1.0 No license field.
npm WARN optional dep failed, continuing fsevents@0.3.8
|
> node-sass@2.1.1 install /net/home/blake.chambers/workspace/torso-brec-sandbox/node_modules/quick-sip/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js


> node-sass@2.1.1 postinstall /net/home/blake.chambers/workspace/torso-brec-sandbox/node_modules/quick-sip/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

`linux-x64-node-0.12` exists; testing
Binary is fine; exiting
hbsfy@2.2.1 node_modules/hbsfy
├── xtend@3.0.0
└── through@2.3.8

gulp@3.9.0 node_modules/gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.5
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.1.0 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── minimist@1.1.2
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── semver@4.3.6
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

handlebars@3.0.0 node_modules/handlebars
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── source-map@0.1.43 (amdefine@1.0.0)
└── uglify-js@2.3.6 (async@0.2.10, optimist@0.3.7)

aliasify@1.7.2 node_modules/aliasify
└── browserify-transform-tools@1.3.3 (through@2.3.8, falafel@1.0.1)

brec-tables@0.2.5 node_modules/brec-tables
├── path@0.11.14
├── brec-base@0.1.4
└── datatables@1.10.7 (jquery@2.1.4)

backbone-torso@0.1.3 node_modules/backbone-torso
├── underscore@1.8.2
├── backbone-nested@2.0.3
├── backbone@1.1.2
├── backbone.stickit@0.8.0
└── jquery@2.1.3

quick-sip@0.1.3 node_modules/quick-sip
├── color-log@0.0.2
├── run-sequence@1.1.2 (chalk@1.1.0)
├── gulp-tap@0.1.3 (event-stream@3.1.7)
├── vinyl-source-stream@1.1.0 (vinyl@0.4.6, through2@0.6.5)
├── gulp-sourcemaps@1.5.2 (graceful-fs@3.0.8, convert-source-map@1.1.1, strip-bom@1.0.0, vinyl@0.4.6, through2@0.6.5)
├── vinyl-buffer@1.0.0 (through2@0.6.5, bl@0.9.4)
├── gulp-concat@2.6.0 (through2@0.6.5, concat-with-sourcemaps@1.0.2)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.1.2, chalk@1.1.0, vinyl@0.5.1, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
├── gulp-load-plugins@0.8.1 (multimatch@2.0.0, findup-sync@0.2.1)
├── del@1.2.0 (is-path-cwd@1.0.0, object-assign@2.1.1, each-async@1.1.1, is-path-in-cwd@1.0.0, globby@2.1.0, rimraf@2.4.2)
├── watchify@2.6.2 (xtend@4.0.0, through2@0.5.1, chokidar@0.12.6)
├── gulp-cssmin@0.1.7 (filesize@2.0.4, graceful-fs@2.0.3, map-stream@0.0.4, gulp-rename@1.1.0, temp-write@0.1.1, gulp-util@2.2.20, clean-css@3.3.8)
├── gulp-uglify@1.2.0 (deap@1.0.0, through2@0.6.5, vinyl-sourcemaps-apply@0.1.4, uglify-js@2.4.19)
├── lodash@3.10.1
├── browserify@9.0.8 (https-browserify@0.0.0, tty-browserify@0.0.0, builtins@0.0.7, constants-browserify@0.0.1, process@0.10.1, path-browserify@0.0.0, os-browserify@0.1.2, isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, defined@0.0.0, stream-browserify@1.0.0, shell-quote@0.0.1, commondir@0.0.1, domain-browser@1.1.4, xtend@3.0.0, duplexer2@0.0.2, deep-equal@1.0.0, shallow-copy@0.0.1, querystring-es3@0.2.1, assert@1.3.0, punycode@1.2.4, util@0.10.3, through2@1.1.1, parents@1.0.1, concat-stream@1.4.10, events@1.0.2, has@1.0.1, timers-browserify@1.4.1, read-only-stream@1.1.1, console-browserify@1.1.0, vm-browserify@0.0.4, subarg@1.0.0, http-browserify@1.7.0, readable-stream@1.1.13, shasum@1.0.1, url@0.10.3, labeled-stream-splicer@1.0.2, buffer@3.4.1, resolve@1.1.6, browser-resolve@1.9.0, glob@4.5.3, JSONStream@0.10.0, deps-sort@1.3.9, syntax-error@1.1.4, browser-pack@4.0.4, crypto-browserify@3.9.14, browserify-zlib@0.1.4, insert-module-globals@6.5.2, module-deps@3.9.0)
├── gulp-autoprefixer@2.3.1 (object-assign@2.1.1, through2@0.6.5, vinyl-sourcemaps-apply@0.1.4, postcss@4.1.16, autoprefixer-core@5.2.1)
└── gulp-sass@1.3.3 (clone@0.1.19, map-stream@0.1.0, vinyl-sourcemaps-apply@0.1.4, node-sass@2.1.1)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn gulp ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

**Comment by mandragorn** [comment]
What operating system was this run on?

**Comment by blakejwc** [comment]
Ubuntu 12

**Comment by blakejwc** [comment]
Update: (also, now on Ubuntu 14)

I did a global install of gulp:

```
$ npm install --global gulp
```

and that solved the immediate problem, but not the issue with the vague error.

Should I close this issue and open a new one for error handling being less than desirable?
Or, is it possible to make it so global gulp isn't necessary for running this generator... is that possible?

**Comment by blakejwc** [comment]
https://github.com/vecnatechnologies/generator-torso-brec/pull/24 was merged, I believe this issue is closed.
